# Ubuntu 24.04 기반 이미지 사용
FROM ubuntu:24.04

# 비대화형 모드 설정
ENV DEBIAN_FRONTEND=noninteractive

# 시스템 업데이트 및 Python3, pip 설치
RUN apt-get update && \
    apt-get install -y python3 python3-pip && \
    rm -rf /var/lib/apt/lists/*

# 소스 코드 복사 및 작업 디렉토리 설정
COPY . /app
WORKDIR /app


# requirements.txt에 정의된 패키지 설치 (PEP 668 이슈를 회피하기 위해 --break-system-packages 옵션 사용)
RUN pip3 install --no-cache-dir --break-system-packages -r requirements.txt