# Ubuntu 24.04 기반 이미지 사용
FROM ubuntu:22.04

# 비대화형 모드 설정
ENV DEBIAN_FRONTEND=noninteractive

# 시스템 업데이트 및 Python3, pip 설치
RUN apt-get update && \
    apt-get install -y python3 python3-pip && \
    rm -rf /var/lib/apt/lists/*

# 소스 코드 복사 및 작업 디렉토리 설정
COPY . /app
WORKDIR /app

RUN pip3 install --no-cache-dir -r requirements.txt